---
title: "MS_Discussion"
author: "Author"
date: "`r Sys.Date()`"
output: html_document
---

Prior literature has noted that health economic models routinely have limitations in transparency [@Jalali2021; @McManus2019; @Bermejo2017; @Ghabri2019], reuse [@Feenstra2022; @Emerson2019], and being kept up to date [@Sampson2017; @10.3389/fpubh.2022.899874]. These limitations not only pose ethical risks such as those we have described, but are practical barriers to achieving potential exciting enhancements to health economic modelling practice such as improved model transferability [@munthe2019systematic; @barbieri2010international], greater use of reference models [@Afzali2013], living health technology assessments [@thokala2023living] and leveraging the analytic capabilities of machine learning [@padula2022machine].

It is important that the health economics community engages with the ethical dimensions of how health economic models are implemented as software. Recent developments in Large Language Models (LLMs) mean software developers are confronted with novel ethical issues including: increased risk of security flaws; a potential need to add restrictions to open-source licensing; environmentally harmful levels of computing power; and concerns about model explainability and unintended consequences [@ozkaya2023application]. Early work exploring the use of LLMs in CHEM development has already been undertaken [@poirrier2023msr26]. Many of the active ethics debates in the computer science community are therefore likely to become increasing relevant to health economists and public health researchers. Documents such as the World Health Organisation's recent guidance on generative artificial intelligence [@world2024ethics] will be important reference points for how the health economics discipline navigates emerging ethical themes in CHEM development.

Meeting all six TRU criteria we propose is more likely when a CHEM has been implemented as an open-source project<!-- and model transferability -->. It should be noted that the ethical dimensions of open-source software development are broader than the issues we have discussed here, including issues relating to social contracts, contributor autonomy and public goods [@grodzinsky2003ethical]. There are also important barriers to growing the (currently paltry) number of open-source CHEMs. These barriers include health economist concerns about intellectual property, confidential data, the risk of model misuse and the resources required for model maintenance [@Pouwels2022; @Wu2019]. Commercial considerations, for example when health economic models are owned by pharmaceutical companies and consultancies, may also limit the public availability of models and their constituent code and data [@Feenstra2022]. Other barriers relate to <!-- model generalisability and transferability and  -->the software platforms in which CHEMs are authored [@Pouwels2022].

Recent efforts to develop the open-source CHEMs field include an initiative to develop a suite of open source CHEMs addressing different health conditions in the United States [@Jansen2019] and a Canadian platform facilitating access to and validation of multiple CHEMs [@harvard2022developing]. It has also been recommended that training curricula for current and future health economists need to develop some foundational software development skills [@kindilien2021role]. Education efforts to develop such skills could be reinforced with best-practice scientific computing guidance for health economists. Adherence to good practice guidance is an essential requirement for healthcare modelling [@Erdemir2020], but guidelines for implementing open source CHEMs remain scarce, piecemeal and need improving [@Sampson2019]. Health economists also need to be able to access reliable and up to date legal advice about the implications of alternative approaches to software licensing.

<!-- Move to discussion--><!-- In health economics the related and enabling concept of reference models has been recommended [@Afzali2013].  -->
<!-- Transferring a health economic model developed for one jurisdiction for application in another typically involves retaining some features and updating others [@barbieri2010international]. However, models do not always make implementation choices (for example, use of concepts with standardised meanings across jurisdictions)<!-- [@garcia2021cost] -->  <!-- facilitate such selective re-use. -->
<!-- Open-source CHEMs remain rare [@Feenstra2022; @Emerson2019]. The software used to develop CHEMs was identified as a barrier to open-source model implementations by participants in a 2020 survey of health economists [@Pouwels2022]. Other reported barriers relate to difficulties in generalising models, updating models and transferring model data, concerns about the level of public access and lack of interest from decision-makers, and legal, confidentiality and security considerations [@Pouwels2022].  -->

Many of these barriers require significant investments by governments and other research funders in enabling infrastructure and human capital. <!-- A core responsibility of research funders is reducing waste in research [@chalmers2014increase]. Investments in modelling projects might generate greater social returns if they supported the project activities necessary to develop CHEMs that are easily understood, widely reused and well maintained.  --> Investment strategies that have previously been recommended for development of the health economic research field include support for harmonised ethical standards for model development [@10.3389/fpubh.2017.00068], methodological innovation to improve model transferability [@craig2018taking], networks of modellers working on common health conditions [@Sampson2019], and  centralized infrastructure such as open-source model repositories [@Pouwels2022] and a standard platform for model implementations [@Ghabri2019]. 

<!-- Each of these strategies could benefit from enabling technical infrastructure, for example software frameworks that support the development of CHEMs that meet ethical criteria. We are currently engaged in developing a prototype of one such software framework [@ready4fw2024]. -->




<!-- Adherence to good practice guidance is an essential requirement for healthcare modelling [@Erdemir2020] and there is a need for better and comprehensive guidelines about how health economists should implement health economic models as software.  -->


<!-- Development of software frameworks to support ethical CHEM implementations could enable and enhance each of these strategies. --> 



<!-- As illustrated by Table \@ref(tab:checktb), we have developed a prototype software framework that can be used to implement youth mental health CHEMs that largely satisfy our TRU criteria. However, in its current form our software framework is too fragile to be recommended as anything more than a prototype for supporting the development needs of other modelling teams and projects. We developed our prototype software framework primarily to address the user requirements of one group – ourselves. Factors such as user enjoyment, usability, active user-community and supporting resources influence adoption of software frameworks [@myllarniemi2018development]. We currently lack the resources required to  address these issues for our software framework. -->

<!-- However, our prototype has a number of features that future work on CHEM software frameworks may find useful to incorporate. Firstly, developing a software framework to work within an existing and widely used open-source programming language such as R, can keep framework scope relatively narrow. This makes it more tractable to develop, maintain and learn, and facilitates integration with other modelling tools written in that language (e.g., the dependency libraries we list in Table \@ref(tab:cpkgs)). Secondly, implementation that combines both object-oriented and functional programming paradigms can avail of the modular and syntactical simplicity benefits of the former, while limiting needless bundling of code artefacts. Thirdly, a sensible trade-off needs to be found between transparent code implementation (which requires clear and sufficiently detailed documentation) and Agile Software Development (for which a foundational principle is prioritising the development of working code over writing documentation [@beck2001manifesto]). Our software framework makes this trade off by enforcing the use of consistent code style conventions and file organisation which in turn enables automated generation of simple documentation at every CHEM module update. All model data-structures and algorithms are therefore always documented (at least minimally, with machine authored content), meaning model developers have a requirement to write customised documentation less frequently. Many of the features of our prototype software framework have the potential to be significantly enhanced through integration with evolving code and documentation authoring capabilities of large language models. -->

<!-- Our software framework provides the outline of a technical solution to some of the challenges of open-source CHEM development. However, better tools alone are insufficient and policy and institutional changes are also required.  -->




<!-- A future software framework for ethical CHEMs would ideally incorporate a base set of features useful to developers of computational models across all domains of public health and health economics, with the capability for community-led extensions that are tailored to the needs of modellers focused on specific health-conditions. Such approaches will likely be important to ensure a sufficient potential user-base to make CHEM software frameworks sustainable. -->










